name: db

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  makedb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: build db
        run: bash makedb.sh

      - name: remove old release
        env:
          GH_TOKEN: ${{ secrets.GTOK }}
          GH_REPO: ${{ github.repository }}
        run: gh release delete $(gh release view -R "${{ github.server_url }}/${{ github.repository }}" --json tagName -q .tagName) --cleanup-tag -y
        continue-on-error: true

      - name: publish release
        env:
          GH_TOKEN: ${{ secrets.GTOK }}
          GH_REPO: ${{ github.repository }}
        run: >
          gh release create $(date +"%m%d%Y")
          owcdb.txt
          --draft=false
          --latest
          -t "Community profiles DB"
          -n "This db is always up to date"


